# Generated by Django 4.0.4 on 2022-07-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('ended_class', models.CharField(max_length=200)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_phone_number', models.CharField(max_length=200)),
                ('health_problems', models.CharField(max_length=1500)),
            ],
        ),
    ]
